// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AllianceGroupRow = { captureSessionId?: number, groupId: number, groupName: string, legionId: number, legionName: string, memberCount: number, observedAt: string, rawJson: string, };
