// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AllianceFacilityRow = { name: string, facilityType: string, cfgId: number, carrierId: string, level: string, state: string, coord: string, operatorName: string, benefit: number, effect: string, };
