// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AllianceLogRow = { captureSessionId: number, time: string, category: string, section: string, actor: string, target: string, text: string, };
