// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AllianceMemberRow = { avatarId: string, name: string, official: string, profession: string, isOnline: number, legion: string, prosperity: number, contribution: number, merit: number, seasonScore: number, lastOfflineTs: number, demolition: number, coord: string, status: string, };
