// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AllianceFacilityRow } from "./AllianceFacilityRow";
import type { AllianceGroupRow } from "./AllianceGroupRow";
import type { AllianceMemberRow } from "./AllianceMemberRow";
import type { CaptureSessionRow } from "./CaptureSessionRow";
import type { ExportJobRow } from "./ExportJobRow";
import type { LineupProfileRow } from "./LineupProfileRow";
import type { MemberBindingRow } from "./MemberBindingRow";
import type { RawArtifactRow } from "./RawArtifactRow";
import type { WorkspaceRecord } from "./WorkspaceRecord";
import type { WorkspaceSummary } from "./WorkspaceSummary";

/**
 * 前端 IPC 用的瘦身 bundle（阶段3a）：只携带 summary + 小表元数据。
 * 战报明细、同盟日志、成员/设施快照大表已移除，前端改走分片命令：
 * get_battle_reports_paged / get_alliance_logs_paged / get_member_snapshots。
 */
export type AppBundle = { summary: WorkspaceSummary, workspaces: Array<WorkspaceRecord>, captureSessions: Array<CaptureSessionRow>, rawArtifacts: Array<RawArtifactRow>, exportJobs: Array<ExportJobRow>, allianceMembers: Array<AllianceMemberRow>, allianceFacilities: Array<AllianceFacilityRow>, allianceGroups: Array<AllianceGroupRow>, lineupProfiles: Array<LineupProfileRow>, memberBindings: Array<MemberBindingRow>, };
