// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionSnapshot } from "./ConnectionSnapshot";
import type { LogEntry } from "./LogEntry";
import type { PacketRecord } from "./PacketRecord";
import type { ReportRecord } from "./ReportRecord";
import type { SessionRecord } from "./SessionRecord";

export type AppSnapshot = { 
/**
 * 单调递增的快照版本号：任何快照数据变化（连接状态/抓包/战报/历史目录等）
 * 都会 +1。前端用事件 `battle-grabber://snapshot-updated` 收到新版本号，
 * 再带 `sinceVersion` 调 get_app_snapshot 判断是否需要拉全量。
 */
version: number, scanWorkspace: string, workspaceOutputDir: string, connection: ConnectionSnapshot, logs: Array<LogEntry>, packets: Array<PacketRecord>, reports: Array<ReportRecord>, sessions: Array<SessionRecord>, alliancePackets: Array<Record<string, unknown>>, 
/**
 * 记录条数（轻量计数，前端据此判断是否需要重新拉取）
 */
allianceRecordCount: number, };
