// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppSnapshot } from "./AppSnapshot";

/**
 * get_app_snapshot 的返回体：`changed=false` 时不携带 snapshot（轻量「无更新」
 * 应答），前端凭 `version` 与事件流保持缓存一致。
 */
export type AppSnapshotResponse = { changed: boolean, version: number, snapshot?: AppSnapshot, };
