// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BattleReportRow = { workspaceId?: number, allianceId?: number, time: string, battleCode: string, enemy: string, enemyPlayer: string, result: string, 
/**
 * 实际战斗结束回合（endRound）。历史实现误读 match_type，已修正为 end_round。
 */
round: number, location: string, lineup: string, battleId: string, battlefieldEnvironmentJson: string, };
