// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BuildingSnapshotRow = { id: number, captureSessionId: number, observedAt: string, buildingName: string, facilityType: string, facilityTypeId: number, roleFacilityType: number, cfgId: number, carrierId: string, level: string, state: string, statusId: number, coordinateX: number, coordinateY: number, operatorAvatarId: string, operatorName: string, benefit: number, mineCount: number, maxMineCount: number, effect: string, rawJson: string, };
