// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 阶段3a 采集完成事件 payload：start_capture_session 后台闭包在
 * finish_capture_session 之后（成功与失败路径都会）emit
 * `"capture-session-finished"`，前端据此刷新采集会话列表。
 */
export type CaptureSessionFinished = { sessionId: number, ok: boolean, error?: string, };
