// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CaptureManifestArtifactSummary = { id: number, path: string, sha256: string, artifactType: string, };
