// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CapturePreviewCounts = { memberSnapshots: number, legionGroups: number, unionLogEvents: number, buildingSnapshots: number, battleBlocks: number, lineupProfiles: number, 
/**
 * 同盟情报快照（排行榜/红度/赛季战队/主公簿/同盟建筑/同盟历史）数量
 */
intelSnapshots: number, 
/**
 * 情报快照下的明细条目总数
 */
intelEntries: number, };
