// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureManifestArtifactSummary } from "./CaptureManifestArtifactSummary";
import type { CapturePreviewCounts } from "./CapturePreviewCounts";

export type CaptureSessionSummaryRecord = { collector: string, status: string, note: string, capture: import("./CaptureSessionCapture").CaptureSessionCapture, sidecarSessionId?: string, previewInsertCounts?: CapturePreviewCounts, rawArtifact?: CaptureManifestArtifactSummary, };
