// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureSessionSummaryRecord } from "./CaptureSessionSummaryRecord";

export type CaptureSessionRow = { id: number, captureType: string, status: string, startedAt: string, finishedAt: string | null, summaryJson?: string, summary?: CaptureSessionSummaryRecord, };
