// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CollectorFlowStatus = { flow: string, expectedArtifacts: Array<string>, navigation: Array<string>, nextProbe?: string, preview?: Record<string, unknown>, };
