// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CollectorCapturePayload = { collectorMode: string, captureType: string, flow: string, expectedArtifacts: Array<string>, navigation: Array<string>, nextProbe?: string, preview?: Record<string, unknown> | null, runtime?: Record<string, unknown> | null, evidence?: Record<string, unknown> | null, };
