// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectorFlowStatus } from "./CollectorFlowStatus";

export type CollectorStatus = { available: boolean, mode: string, message: string, captureFlows: { [key in string]?: CollectorFlowStatus }, runtimeProbe?: unknown, };
