// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SQL-side comparison counters for a single date window.
 * Populated by `Database::query_comparison_stats`.
 */
export type ComparisonStats = { members: number, buildings: number, battles: number, sessions: number, };
