// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CrossWorkspacePowerPoint = { workspaceId: number, workspaceName: string, date: string, memberCount: number, totalWeeklyMerit: number, totalSeasonScore: number, };
