// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportJobRow = { id: number, createdAt: string, jobKind: string, format: string, target: string, status: string, outputPaths: Array<string>, };
