// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 同盟情报快照行。
 *
 * 一个"主题"一行：某个榜单（繁荣榜·司仓）、某位玩家的红度普查、某支赛季战队。
 * `payloadJson` 保留游戏原始载荷，使协议演进后可以只改解析器重放历史数据。
 */
export type IntelSnapshotRow = { id: number, workspaceId: number, allianceId: number, 
/**
 * server_rank | hero_rating | season_team | player_profile | union_building | union_history
 */
kind: string, subjectKey: string, subjectLabel: string, observedAt: string, entryCount: number, metricsJson: string, sourceFunc: string, };
