// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 同盟情报明细行（榜单名次 / 战队成员 / 武将红度行）。
 */
export type IntelEntryRow = { id: number, snapshotId: number, kind: string, rank: number, subjectKey: string, name: string, unionName: string, value: number, extraJson: string, };
