// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LineupMatchupRow = { id: number, workspaceId: number, attackerAvatarId: string, attackerPlayerName: string, attackerLineupKey: string, attackerLineupLabel: string, defenderAvatarId: string, defenderPlayerName: string, defenderLineupKey: string, defenderLineupLabel: string, outcome: string, battleTime: string, battleCode: string, observedAt: string, 
/**
 * S3 战报分类：战斗模式（1 野战/2 攻城/3 守城/4 集结），0 未知
 */
matchType: number, 
/**
 * 战报原始 combatType，0 未知
 */
combatType: number, 
/**
 * 场景 ID，0 未知
 */
scenarioId: number, 
/**
 * 实际结束回合数
 */
endRound: number, 
/**
 * 战斗地点坐标
 */
location: string, };
