// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LineupMatchupInput = { workspaceId: number, attackerAvatarId: string, attackerPlayerName: string, attackerLineupKey: string, attackerLineupLabel: string, defenderAvatarId: string, defenderPlayerName: string, defenderLineupKey: string, defenderLineupLabel: string, outcome: string, battleTime: string, battleCode: string, 
/**
 * S3 战报分类（可选，缺省 0）
 */
matchType: number, combatType: number, scenarioId: number, endRound: number, location: string, };
