// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LineupProfileRow = { playerId?: number, allianceId?: number, label: string, player: string, heroes: string, source: string, confidence: string, };
