// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineupMatchupRow } from "./LineupMatchupRow";
import type { LineupStatRow } from "./LineupStatRow";

export type LineupAnalysisBundle = { stats: Array<LineupStatRow>, matchups: Array<LineupMatchupRow>, };
