// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionSnapshot } from "./ConnectionSnapshot";
import type { LogEntry } from "./LogEntry";
import type { PacketRecord } from "./PacketRecord";
import type { ReportRecord } from "./ReportRecord";

export type LiveCaptureSnapshot = { scanWorkspace: string, workspaceOutputDir: string, connection: ConnectionSnapshot, logs: Array<LogEntry>, packets: Array<PacketRecord>, reports: Array<ReportRecord>, 
/**
 * P2-2 Phase 1：见 `AppSnapshot` 的说明——轮询快照不再携带全量记录
 * （此前这里是「每次轮询都整包 clone + 序列化」的主要风险点）。
 * 记录改由 `get_alliance_records` 按需拉取。
 */
allianceRecordCount: number, };
