// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemberBindingRow = { playerId?: number, allianceId?: number, name: string, avatar: string, alliance: string, status: string, updated: string, 
/**
 * 是否为当前生效绑定（valid_to IS NULL）。历史行 valid_to 非空时为 false。
 */
isActive: boolean, };
