// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemberActivityAlertRow = { avatarId: string, avatarName: string, officialName: string, weeklyContribution: number, weeklyMerit: number, lastOfflineTs: number, observedAt: string, };
