// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberActivityAlertRow } from "./MemberActivityAlertRow";

export type MemberActivityAlerts = { offlineMembers: Array<MemberActivityAlertRow>, lowContribution: Array<MemberActivityAlertRow>, };
