// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PacketRecord = { sessionId: string, seq: number, msgId: number, protoName: string, timestamp: string, localDir: string, metaPath: string, contentLength: number, };
