// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntelEntryRow } from "./IntelEntryRow";

export type PagedIntelEntries = { rows: Array<IntelEntryRow>, total: number, };
