// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AllianceLogRow } from "./AllianceLogRow";

/**
 * 同盟日志分页结果（阶段3a 分片命令 get_alliance_logs_paged 的返回类型）。
 */
export type PagedAllianceLogs = { rows: Array<AllianceLogRow>, total: number, };
