// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberSnapshotRow } from "./MemberSnapshotRow";

/**
 * 成员快照分页结果（阶段3a 分片命令 get_member_snapshots 的返回类型）。
 * latest_only=true 时 total 为去重后的成员人数，否则为快照总行数。
 */
export type PagedMemberSnapshots = { rows: Array<MemberSnapshotRow>, total: number, };
