// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntelSnapshotRow } from "./IntelSnapshotRow";

export type PagedIntelSnapshots = { rows: Array<IntelSnapshotRow>, total: number, };
