// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BattleReportRow } from "./BattleReportRow";

/**
 * 战报分页结果（阶段3a 分片命令 get_battle_reports_paged 的返回类型）。
 * rows 为当前页数据，total 为满足过滤条件的总行数（用于前端分页器）。
 */
export type PagedBattleReports = { rows: Array<BattleReportRow>, total: number, };
