// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RawArtifactRow = { id: number, captureSessionId: number, artifactType: string, path: string, sourceModule: string | null, sourceFunc: string | null, capturedAt: string, sha256: string | null, sensitiveScanStatus: string, };
