// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReportRecord = { sessionId: string, id: string, txt: string, md: string, csv: string, json: string, html: string, battleJson: string, battleMd: string, eventCount: number, summary: unknown, battleDetails: unknown, };
