// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveLineupProfileRequest = { workspaceId: number, allianceId: number | null, playerName: string, playerAvatarId: string | null, side: string | null, label: string, heroes: Array<string>, sourceBattleId: string | null, confidence: string, notes: string | null, };
