// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessInfo } from "./ProcessInfo";
import type { ReportRecord } from "./ReportRecord";

export type SessionRecord = { id: string, source: string, outputDir: string, summaryPath: string, generatedAt: string, process: ProcessInfo | null, installed: boolean, packetCount: number, reports: Array<ReportRecord>, reportCount: number, allianceCount: number, };
