// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceSummary = { workspaceCount: number, allianceCount: number, captureSessionCount: number, rawArtifactCount: number, exportJobCount: number, memberSnapshotCount: number, buildingSnapshotCount: number, battleBlockCount: number, lineupProfileCount: number, databasePath: string, };
