// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceRecord = { id: number, name: string, serverName: string, seasonName: string, allianceId?: number, allianceName?: string, allianceGameId?: string, createdAt: string, updatedAt: string, };
